### ISSUE TITLE
ModuleNotFoundError: No module named 'lib' on import 

### ISSUE THREAD

**Issue by mladeny** [tfrancoi/odoo_csv_import#10]
I'm having trouble importing the module from a python script

`from odoo_csv_tools import import_threaded`

results in 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mladenyakimov/.virtualenvs/odoo/lib/python3.6/site-packages/odoo_csv_tools/__init__.py", line 1, in <module>
    import lib
ModuleNotFoundError: No module named 'lib'`

**Comment by mladeny** [comment]
Does this module work with Python3 or Python2 only?

**Comment by mladeny** [comment]
seems like the import works with Python2... any idea if this will be ported to Python3?

It's available in the pip3 package manager, so I'd assume it should work with Python3...?

**Comment by tfrancoi** [comment]
Hello, 
Indeed it was not compatible with python 3. It's the case now with the version 2.0.0
https://pypi.python.org/pypi/odoo-import-export-client/2.0.0 

The code is not yet in master, it's available on the branch https://github.com/tfrancoi/odoo_csv_import/tree/migration-p3

**Comment by tfr-odoo** [comment]
Master is now compatible with python 3
