### ISSUE TITLE
More record from one row

### ISSUE THREAD

**Issue by taifu** [tfrancoi/odoo_csv_import#14]
Usually customers give us data with these fields:

`CODE;NAME;PHONE;INVOICING_CONTACT;INVOICING_PHONE;...`

These should be imported as a main partner and an invoicing contact partner with main partner as parent_id.

I find I can do this writing res.partner.csv with one mapping and res.partner.cs2 with a second mapping. res.partner.2.csv or res.partner.csv2 wont do.

Is mine (res.partner.cs2) the proper way to write more res.partner file?

**Comment by tfrancoi** [comment]
This is exactly the way to do it.
See my example: https://github.com/tfrancoi/odoo_import_example/blob/11.0/supplier.py#L11

With one file you can define as many mapping you want and thus generate as many file to import as you want.

**Comment by taifu** [comment]
Maybe I did not say it clear enough. The question is about the name of the file: partner.cs2.
Do you need to change the extension? You can't keep the same name or the second mapping will overwrite the first file. I didn't find.

**Comment by tfr-odoo** [comment]
It's better to have different names. Otherwise the first file will be erase by the second. 
The file name does not really matter as long as you give the parameter --model at the import.
