### ISSUE TITLE
[Track] odoo_csv_import XOE Labs' interpretation

### ISSUE THREAD

**Issue by blaggacao** [tfrancoi/odoo_csv_import#15]
This is too custom to formalize (yet), but I want to share.

https://gist.github.com/blaggacao/ba83a7e500c202cf842010cfddb25e15

In an ideal world, we could build a component based library for Odoo imports, leveraging excellent acsone's [`click-odoo`](https://github.com/acsone/click-odoo).

My main use case: I want to run Odoo-Loaders as microservices consuming datastreams and giving feedback on another channel to remote clients*, so a component based approach would just be ideal for greater convergence and collaboration.
See also discussion here: https://github.com/acsone/click-odoo-contrib/issues/11#issuecomment-428232104

\* Why? Integrate with ETL tools.

**Comment by tfrancoi** [comment]
Hello,
Your link is not accessible, I guess this is a private repo. 

I just check the click library which is basically odoo shell embedded in your python script, this is not at all the philosophy of my library. 
The goal is to use the rpc call to parallelize calls and take advandage of the many worker available on the server.

I'm open to a patch that would allow to take the file to import from a pipe.
You can call https://github.com/tfrancoi/odoo_csv_import/blob/master/odoo_csv_tools/import_threaded.py#L174 import_data with a file descriptor for the parameter file_csv, and fail_file

**Comment by blaggacao** [comment]
@tfrancoi Just fixed the link to the gist, sorry.

I'm still thinking about a basic design principle for most reusable components.

My idea was that click-odoo script, as an Odoo Server API extensions, could conduct DAG analysis for relations between multiple files and also analyse hierarchy tables to autosort them for internal dependencies (make group-by config obsolete)

The only requirement: 

- click-odoo needs a copy of the target codebase in it's environment (which is rather realistic to provide)
- Note I depend on an ugly Odoo patch to reach that goal in my interpretation: https://gist.github.com/blaggacao/ba83a7e500c202cf842010cfddb25e15#file-utils-py-L186

Then, loading can be done using local computing resources (eg. a more powerful machine - I've loaded several million records in just over 4 days with my odoo_csv_import derivate *) and result can be sent directly to the (remote) database.

Especially the idea to provide individually scalable resources to the ETL workflow seems appealing to me.

\* It would require temporary production scaling in most cases. Why production? because we usually load the accounting history with some delay after going live because the ETL process takes some while.

**Comment by blaggacao** [comment]
I also think since ...
- odoo/odoo@b1e83fd
- odoo/odoo@d5b687a

... the default batch size can be significantly increased.

@tfrancoi In this context is `groupby` config still necessary??? -> I'm short on understanding on this one.

**Comment by blaggacao** [comment]
@tfrancoi A possible CLI UX... https://github.com/acsone/click-odoo-contrib/pull/15
There, we can join for a happy refactoring, should you be interested...

**Comment by blaggacao** [comment]
@tfrancoi Would it be reasonable to assume that hierarchy tables should not be scheduled on multiple threads, but be collocated on a single thread to avoid complicated cross-thread-same-dataframe dependency locks? After all, hierarchy tables tend to be rather short.

**Comment by blaggacao** [comment]
@tfrancoi (FYI)
This is what I've come up so far: https://pypi.org/project/click-odoo-loader/
And here is the source: https://github.com/xoe-labs/click-odoo-loader
