### ISSUE TITLE
[feature] Import image by url

### ISSUE THREAD

**Issue by Navds** [tfrancoi/odoo_csv_import#22]
Odoo can import a csv file with an image column containing an URL. This file cannot be imported with odoo_import_thread.py because it expects a base64.

**Comment by tfrancoi** [comment]
Hello, 
The feature in odoo happen before the call to the method load, so it's not possible to call the method load with url and expect to have them imported.

but you can use the transformation tool to process your csv prior the import to convert your url into a base64.

I have actually add in version 2.2.0 a new tool to convert path and url into base 64, you can see https://github.com/tfrancoi/odoo_csv_import/blob/master/odoo_convert_url_to_image.py
