### ISSUE TITLE
Importing journal items.

### ISSUE THREAD

**Issue by joao-jeronimo** [tfrancoi/odoo_csv_import#24]
Hello.

I was trying to import journal items, but the journal entry needs the credit and debit totals to be balanced. So it gives me the following error:
{'rows': {'from': 2, 'to': 2}, 'record': 2, 'type': 'error', 'message': "Unknown error during import: <class 'odoo.exceptions.UserError'>: ('Cannot create unbalanced journal entry.', '')", 'moreinfo': 'Resolve other errors first'}

Any known solution for this problem?

Thanks.
João Jerónimo

**Comment by jad-odoo** [comment]
Hello,

If you import the account moves and the account move lines separately, you must disable the balance check when importing the account move lines. Use the context key 'check_move_validity' to do so.
ex: odoo_import_thread.py -c .... -f .... -m account.move.line  --context="{'check_move_validity': False}"

You can also import the account moves and the account move lines in the same file and use the option --o2m.

More details here: https://github.com/tfrancoi/odoo_csv_import#importing-account-move-lines

Kindly,
Jean Adam

**Comment by joao-jeronimo** [comment]
Thank you.
