### ISSUE TITLE
[Exports] How to get ids ?

### ISSUE THREAD

**Issue by ejemba** [tfrancoi/odoo_csv_import#26]
Hi,
 when trying differents export instead of getting actual id I get a string representation

`./env/bin/odoo_export_thread.py -c=config.ini --model=res.partner --worker=4 --field="id,name,phone,website,street,city,country_id" --file=out.cs`
gives
```
...
"__export__.res_partner_172_7a1a6fdb";"FirstName LastName";"";"";"";"Montigny les cormeilles";"France"
...
```
- id **gives** `__export__.res_partner_172_7a1a6fdb`
-  country_id **gives** France

in both case I expected just integers .

How can I get integers ? not an arbitrary string representation ?

**Comment by tfrancoi** [comment]
id give the external_id (that you can find in table ir_model_data)
the many2one like country_id give the name_get of the record
country_id/id give the external id of the record given by the many2one

.id give the database id of the record 
country_id/.id give the database id of the record given by the many2one.

**Comment by ejemba** [comment]
Thank you @tfrancoi you made my day.

Perhaps it can be good to update the doc for the export use case. 
Because all of the id .id stuff/id stuff/.id combination can be hard to discover.

The tools is very very efficient thank you
