### ISSUE TITLE
Is it possible to import odoo users and created_on or by fields with this tool?

### ISSUE THREAD

**Issue by dave08** [tfrancoi/odoo_csv_import#3]
So far I'm doing it with xml, but this tool would be much better!! Thanks for the great work!!

**Comment by tfrancoi** [comment]
It's not possible to write on those field with the ORM it get remove from the value.
I have created a module that allow to use those value in the write and create (and thus import_data) 
https://github.com/tfrancoi/easier_import/tree/10.0/import_metadata

juste need to install this module on your database and pass 'write_metadata' : True in your context, of course it only works with the admin (uid=1). Once your are done with the import you can safely uninstall the module.
