### ISSUE TITLE
[Export] res_currency is exported qith the  field Active = True

### ISSUE THREAD

**Issue by luismata01** [tfrancoi/odoo_csv_import#36]
Hi

When I try to export res_currency with the tool, this only export the records with the field Active = True

How Can I to define --domain =  ['|','active','=',False,'active','=',True] 

Thank's  a lot

**Comment by tfrancoi** [comment]
Hello you can indeed pass the domain as parameter `--domain="['|', ('active', '=', True), ('active', '=', False)]"` but there is a more efficient to ignore the active field with the context active_test=False like this `--context="{'active_test': False}"`

**Comment by luismata01** [comment]
Thank's @tfrancoi 

This was the solution.
